#!/usr/bin/env python3
"""Sign, verify and inspect OTA images for esp32-s3-n16r8-bastion.

Signed image layout (see include/ota_update.h):

    [ ESP-IDF app image ][ 32-byte version, NUL-padded ][ 64-byte Ed25519 signature ]

The signature is Ed25519 over SHA-256(image || version_field), made with the
release private key. The matching public key is compiled into the firmware
(include/ota_public_key.h); the board refuses anything else.

Commands:
    keygen  --key FILE                 create a new private key (64 hex chars = 32-byte seed)
    pubkey  --key FILE [--header FILE] print the public key (hex) / write the C header
    sign    --key FILE --version V --in firmware.bin --out firmware-signed.bin
    verify  --pub HEX|--header FILE --in firmware-signed.bin

The private key may also be supplied through the OTA_SIGNING_KEY environment
variable (hex), which is how CI uses it.
"""

import argparse
import hashlib
import os
import re
import secrets
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)

VERSION_FIELD = 32
SIGNATURE = 64


def load_private_key(path: str | None) -> Ed25519PrivateKey:
    if path:
        seed_hex = Path(path).read_text(encoding="ascii").strip()
    else:
        seed_hex = os.environ.get("OTA_SIGNING_KEY", "").strip()
    if len(seed_hex) != 64:
        sys.exit("private key must be 64 hex characters (32-byte seed); "
                 "pass --key FILE or set OTA_SIGNING_KEY")
    return Ed25519PrivateKey.from_private_bytes(bytes.fromhex(seed_hex))


def public_hex(key: Ed25519PrivateKey) -> str:
    return key.public_key().public_bytes(
        serialization.Encoding.Raw, serialization.PublicFormat.Raw).hex()


def header_text(pub_hex: str) -> str:
    raw = bytes.fromhex(pub_hex)
    rows = [", ".join(f"0x{b:02x}" for b in raw[i:i + 8]) for i in range(0, 32, 8)]
    body = ",\n    ".join(rows)
    return (
        "#pragma once\n\n"
        "#include <stdint.h>\n\n"
        "// Ed25519 public key that OTA images must be signed with.\n"
        "// Generated by scripts/ota_sign.py pubkey --header; the private key\n"
        "// lives outside the repository (GitHub secret OTA_SIGNING_KEY).\n"
        f"// Public key (hex): {pub_hex}\n"
        "constexpr uint8_t kOtaPublicKey[32] = {\n"
        f"    {body}\n"
        "};\n"
    )


def pub_from_header(path: str) -> str:
    text = Path(path).read_text(encoding="utf-8")
    match = re.search(r"Public key \(hex\): ([0-9a-f]{64})", text)
    if not match:
        sys.exit(f"no public key found in {path}")
    return match.group(1)


def cmd_keygen(args: argparse.Namespace) -> None:
    path = Path(args.key)
    if path.exists():
        sys.exit(f"{path} already exists; refusing to overwrite a signing key")
    path.parent.mkdir(parents=True, exist_ok=True)
    seed = secrets.token_bytes(32)
    path.write_text(seed.hex() + "\n", encoding="ascii")
    path.chmod(0o600)
    key = Ed25519PrivateKey.from_private_bytes(seed)
    print(f"private key written to {path} (mode 600)")
    print(f"public key: {public_hex(key)}")


def cmd_pubkey(args: argparse.Namespace) -> None:
    key = load_private_key(args.key)
    pub = public_hex(key)
    if args.header:
        Path(args.header).write_text(header_text(pub), encoding="utf-8")
        print(f"wrote {args.header}")
    print(pub)


def cmd_sign(args: argparse.Namespace) -> None:
    key = load_private_key(args.key)
    image = Path(args.infile).read_bytes()
    if not image or image[0] != 0xE9:
        sys.exit("input does not look like an ESP32 app image (magic 0xE9)")
    version = args.version.encode("ascii")
    if len(version) > VERSION_FIELD - 1:
        sys.exit(f"version longer than {VERSION_FIELD - 1} bytes")
    field = version.ljust(VERSION_FIELD, b"\0")
    digest = hashlib.sha256(image + field).digest()
    signature = key.sign(digest)
    Path(args.outfile).write_bytes(image + field + signature)
    print(f"signed {args.infile} ({len(image)} B) as version {args.version} -> {args.outfile}")
    print(f"sha256(image||version) = {digest.hex()}")


def cmd_verify(args: argparse.Namespace) -> None:
    pub_hex = args.pub or pub_from_header(args.header)
    data = Path(args.infile).read_bytes()
    if len(data) < VERSION_FIELD + SIGNATURE + 1:
        sys.exit("file too short")
    image = data[:-(VERSION_FIELD + SIGNATURE)]
    field = data[-(VERSION_FIELD + SIGNATURE):-SIGNATURE]
    signature = data[-SIGNATURE:]
    digest = hashlib.sha256(image + field).digest()
    Ed25519PublicKey.from_public_bytes(bytes.fromhex(pub_hex)).verify(signature, digest)
    version = field.split(b"\0", 1)[0].decode("ascii", errors="replace")
    print(f"OK: version {version}, image {len(image)} B, signature valid")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("keygen")
    p.add_argument("--key", required=True)
    p.set_defaults(func=cmd_keygen)

    p = sub.add_parser("pubkey")
    p.add_argument("--key")
    p.add_argument("--header")
    p.set_defaults(func=cmd_pubkey)

    p = sub.add_parser("sign")
    p.add_argument("--key")
    p.add_argument("--version", required=True)
    p.add_argument("--in", dest="infile", required=True)
    p.add_argument("--out", dest="outfile", required=True)
    p.set_defaults(func=cmd_sign)

    p = sub.add_parser("verify")
    p.add_argument("--pub")
    p.add_argument("--header")
    p.add_argument("--in", dest="infile", required=True)
    p.set_defaults(func=cmd_verify)

    args = parser.parse_args()
    if args.command == "verify" and not (args.pub or args.header):
        parser.error("verify needs --pub or --header")
    args.func(args)


if __name__ == "__main__":
    main()
